version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "5173:5173"
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "3000:3000"
